[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = default.csv

[env:legit]
build_src_filter = +<legit/>
lib_deps = rweather/Crypto

[env:evil]
build_src_filter = +<evil/>
lib_deps = ayushsharma82/ElegantOTA@^3.1.5
build_flags = -D ELEGANTOTA_USE_ASYNC=0
